### ISSUE TITLE
Nick --- Cuack

### ISSUE THREAD

**Issue by Onii-Chan9** [JavierGonzalez/POL#179]
Cada vez que alguien escriba tui nick te avise con un cuack

**Comment by Shrewd** [comment]
Es algo que siempre quise, y añado además que **los SWF** (que por cierto no parecen funcionar) **dejarán de tener soporte en muchos navegadores en Diciembre de 2020.**

Tengo el sonido del pato (wav de 3KB) pero hay una pega, y es que le chat no distingue la primera carga de cuando se refresca...
Produciéndose un erro si entramos y entramos y ya teníamos nuestro Nick pronunciado o un privado (lo he añadido en ambos)

scripts_all.js?v=13:815 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

Por lo que la solución pasa por añadir una variable que compruebe si se ha iniciado el chat y poner este audio.
No he querido usar otras librerias, por lo que creo que en versiones viejas de IE no funciona...
